dist: bionic
language: python
python:
  - 3.8.2
os:
  - linux
services:
  - xvfb

branches:
  except:
    - gh-pages

cache:
  npm: true
  bundler: true
  pip: true
  apt: true
  directories:
  - node_modules
  - .cache/pip

# the python stuff is for
# https://github.com/travis-ci/travis-ci/issues/8920
# https://github.com/travis-ci/travis-ci/issues/4704#issuecomment-348435959
before_install:
  - sudo lshw -short
  - curl -sL https://github.com/retorquere/zotero-deb/releases/download/apt-get/install.sh | sudo bash
  - travis_retry bash util/install-deb.repo.sh
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install $CLIENT
  - travis_retry sudo ./util/install-beta $CLIENT
script:
  - ls xpi gen
  - ./test/behave --format json.pretty --outfile behave.json --format travis --balance $JOB
  - touch behave.json
  - curl --retry 10 -T behave.json -u "$PCLOUD" https://webdav.pcloud.com/travis/timing/$CLIENT=$TRAVIS_BRANCH=$TRAVIS_JOB_NUMBER=$TRAVIS_EVENT_TYPE.json || echo 'could not upload test timing'
  - touch test/fixtures/loaded.json
  - curl --retry 10 -T test/fixtures/loaded.json -u "$PCLOUD" https://webdav.pcloud.com/travis/used/$CLIENT=$TRAVIS_BRANCH=$TRAVIS_JOB_NUMBER=$TRAVIS_EVENT_TYPE.json || echo 'could not upload test file usage'

after_failure:
  - export fileio=$(curl -F "file=@$HOME/.BBTZ5TEST.log" https://file.io/?expires=2) && echo $fileio

stages:
  - build
  - test
  - release
  - cleanup

jobs:
  include:
  - stage: build
    before_install:
      - nvm install 13.8.0
    script:
      - npm run build
    workspaces:
      create:
        name: build-assets
        paths:
          - xpis
          - gen
    before_deploy:
      - travis_retry sudo snap install hugo --channel=extended
      - hugo version
      - npm --version
      - which npx
      - npm run docs:deploy
    deploy:
      provider: pages
      skip_cleanup: true
      token: $GITHUB_TOKEN
      edge: true
      local_dir: site/public
      keep_history: true
      on:
        branch: master

  - stage: test
    workspaces:
      use: build-assets
    env:
    - CLIENT=zotero
    - JOB=1
  - stage: test
    workspaces:
      use: build-assets
    env:
    - CLIENT=zotero
    - JOB=2
  - stage: test
    workspaces:
      use: build-assets
    env:
    - CLIENT=jurism
    - JOB=1
  - stage: test
    workspaces:
      use: build-assets
    env:
    - CLIENT=jurism
    - JOB=2

  - stage: release
    workspaces:
      use: build-assets
    if: env(TRAVIS_EVENT_TYPE) != cron AND env(TRAVIS_EVENT_TYPE) != pull_request
    before_install:
      - nvm install 13.8.0
    script:
      - npm run release
