language: python
python:
  - 3.6

before_install:
  - curl --silent --location https://github.com/retorquere/zotero-deb/releases/download/apt-get/install.sh | sudo bash
  - travis_retry sudo apt-get update -o Dir::Etc::sourcelist="sources.list.d/zotero.list" -o Dir::Etc::sourceparts="-" -o APT::Get::List-Cleanup="0"
  - travis_retry sudo apt-get install zotero jurism
  - ./check-latest-zotero.py

cache:
  npm: true
  bundler: true
  pip: true
  apt: true
  directories:
  - node_modules
  - vendor/bundle
  - .cache/pip

script: |
  #set -e
  #set -x

  gem install bundler
  gem update bundler
  bundle config
  bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3

  #git submodule sync && git submodule update --init --recursive

  if [[ "$TRAVIS_COMMIT_MESSAGE" == *"#trace"* ]]; then
    export TRACE=true
  fi

  if [[ "$TRAVIS_EVENT_TYPE" == "cron" ]] || [[ ! -z "$TRAVIS_TAG" ]] || [[ "$TRAVIS_COMMIT_MESSAGE" == *"#nightly"* ]]; then
    export NIGHTLY=""
    export TRACE=true
  else
    export NIGHTLY="and not @nightly"
  fi

  xvfb-run bundle exec cucumber --format pretty --strict --tags "$CLUSTER $NIGHTLY"

after_failure:
  curl --upload-file ~/.BBTZ5TEST.log https://transfer.sh/BBTZ5TEST.log

jobs:
  include:
  - stage: test
    env:
    - ZOTERO=zotero
    - CLUSTER="@test-cluster-1"

  - stage: test
    env:
    - ZOTERO=zotero
    - CLUSTER="not @test-cluster-1"

  - stage: test
    env:
    - ZOTERO=jurism
    - CLUSTER="@test-cluster-1"

  - stage: test
    env:
    - ZOTERO=jurism
    - CLUSTER="not @test-cluster-1"

  - stage: release
    install: true
    before_install: true
    script: |-
      if [[ "$TRAVIS_EVENT_TYPE" != "cron" && "$TRAVIS_EVENT_TYPE" != "pull_request" ]]; then
        pip install -r requirements.txt
        npm run build
        npm run release
        # curl --upload-file xpi/zotero-better-bibtex*.xpi https://transfer.sh/zotero-better-bibtex.xpi
      fi
    after_failure: true
