# Dependencies
markdown:         redcarpet
redcarpet:
  # enable auto ids for redcarpet
  extensions:    ["with_toc_data"]
highlighter:      pygments

# Permalinks
permalink: /:categories/:title

# Setup
title:            "Zotero: Better BibTeX"
#tagline:          'Making Zotero all it can be for us LaTeX holdouts'
description:          'Making Zotero all it can be for us LaTeX holdouts'
baseurl:          http://zotplus.github.io/zotero-better-bibtex

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

github:
  repo:           https://github.com/poole/hyde

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "page"
