# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            "Zotero: Better BibTeX"
#tagline:          'Making Zotero all it can be for us LaTeX holdouts'
description:          'Making Zotero all it can be for us LaTeX holdouts'
url:              http://hyde.getpoole.com
baseurl:          http://zotplus.github.io/zotero-better-bibtex/

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

github:
  repo:           https://github.com/poole/hyde

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "page"
