version: 2

_defaults: &defaults
  working_directory: &working_directory ~/retorquere/zotero-better-bibtex
  shell: /bin/bash --login
  environment:
    CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
    CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
#  docker:
#  - image: circleci/ruby:2.4.3-node
#    command: /sbin/init
  docker:
  - image: retorquere/better-bibtex-zotero-5:0.0.2
    command: /sbin/init
  
_run:
  setenv: &setenv
    command: |-
      echo -e "export CIRCLE_WORKING_DIR=${HOME}/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}" >> $BASH_ENV
      echo -e "export PATH=${PATH}:${HOME}/.yarn/bin:\${CIRCLE_WORKING_DIR}/node_modules/.bin" >> $BASH_ENV
      echo -e "export DISPLAY=:1.0" >> $BASH_ENV
      case $CIRCLE_NODE_INDEX in
        2|3)  echo -e "export ZOTERO=jurism" >> $BASH_ENV
              ;;
        *)    echo -e "export ZOTERO=zotero" >> $BASH_ENV
              ;;
      esac
  ruby: &ruby
    command: gem install bundler && gem update bundler && bundle config && (bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3)
    no_output_timeout: 180s
  node: &node
    command: yarn install

jobs:
  build:
    <<: *defaults

    steps:
    - run: *setenv
    - checkout
    - run: git submodule sync && git submodule update --init --recursive
    - restore_cache:
        keys:
        - v3-dep-{{ checksum "package.json" }}
        - v3-dep-
    - run: *node
    - run: *ruby
    - run: mkdir -p bin downloads/zotero downloads/juris-m
    - run: rm -f downloads/*.bz2
    - run: ls -l downloads/*
    - run: ./zotero5_installer.py --client zotero --version latest --location $CIRCLE_WORKING_DIR/bin --datadir profile --replace --cache downloads/zotero
    - run: ./zotero5_installer.py --client jurism --version latest --location $CIRCLE_WORKING_DIR/bin --datadir home    --replace --cache downloads/juris-m
    - run: ls -l downloads/*
    - save_cache:
        key: v3-dep-{{ checksum "package.json" }}
        paths:
          - citation-style-language-locales
          - downloads
          - node_modules
          - vendor/bundle

    - run: yarn run build

    - store_artifacts:
        path: xpi

    - persist_to_workspace:
        root: *working_directory
        paths:
          - bin
          - citation-style-language-locales
          - gen
          - xpi
          - vendor/bundle
          - node_modules

  test:
    <<: *defaults
    parallelism: 4

    steps:
    - run: *setenv
    - checkout

    - attach_workspace:
        at: *working_directory

    # - run: *apt_get
    - run: *ruby

    - run: |-
        set -e

        /usr/bin/expect <<EOF
        spawn "/usr/bin/vnc4passwd"
        expect "Password:"
        send "$VNCPASSWORD\r"
        expect "Verify:"
        send "$VNCPASSWORD\r"
        expect eof
        exit
        EOF

        vnc4server -geometry 1280x1024 -depth 24
        metacity &

        mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS

        if [ "$NIGHTLY" = "true" -o "$CIRCLE_TAG" ]; then
          NIGHTLY_TAGS=""
        else
          NIGHTLY_TAGS="not @nightly and"
        fi

        case $CIRCLE_NODE_INDEX in
          0|2)  export CIRCLE_TESTS="$NIGHTLY_TAGS @test-cluster-1"
                ;;
          *)    export CIRCLE_TESTS="$NIGHTLY_TAGS not @test-cluster-1"
                ;;
        esac

        bundle exec cucumber --strict --tags "$CIRCLE_TESTS"
        cp xpi/zotero-better-bibtex-*.xpi $CIRCLE_ARTIFACTS
        cp -r ~/.BBTZ5TEST/$ZOTERO/better* $CIRCLE_ARTIFACTS
        ls -lh $CIRCLE_ARTIFACTS/*

    - store_test_results:
        path: /tmp/circleci-test-results
    - store_artifacts:
        path: /tmp/circleci-artifacts

    # Deployment
    # Your existing circle.yml file contains deployment steps.
    # The config translation tool does not support translating deployment steps
    # since deployment in CircleCI 2.0 are better handled through workflows.
    # See the documentation for more information https://circleci.com/docs/2.0/workflows/
    # https://circleci.com/docs/2.0/workflows/#using-workspaces-to-share-data-among-jobs
    # https://circleci.com/docs/2.0/configuration-reference/#persist_to_workspace
    # https://circleci.com/docs/1.0/ssh-between-build-containers/

  release:
    <<: *defaults

    steps:
    - run: *setenv
    - checkout
    - attach_workspace:
        at: *working_directory
    - run: yarn run release

  s3form:
    <<: *defaults

    steps:
    - run: *setenv
    - checkout
    - run: *node
    - run: yarn run s3form

workflows:
  version: 2
  build-test-release:
    jobs:
      - build
      - test:
          requires:
            - build
      - release:
          requires:
            - test
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:  
            branches:
              only:
                - master
    jobs:
      - build
      - test:
          requires:
            - build
          context: nightly
      - release:
          requires:
            - test
  s3form:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:  
            branches:
              only:
                - master
    jobs:
      - s3form
