- name: Citation keys
  description: ''
  preferences:
    QuickCopy format:
      default: LaTeX
      description: >-
        Used for drag-and-drop/quick copy using Better BibTeX citekeys. In the
        Zotero "Export" pane, choose `Better BibTeX Quick Copy` as the default
        export format for quick copy, and choose the desired format for the
        drag-and-drop citations here.
      options:
        - LaTeX
        - Cite Keys
        - Pandoc
        - Org-mode (citekey)
        - Org-mode (item ID)
        - org-ref
        - RTF Scan
        - 'Atom (https://atom.io/packages/zotero-citations)'
        - GitBook
        - Select link (citekey)
        - Select link (item ID)
    LaTeX command:
      default: '"cite"'
      description: >-
        Used for drag-and-drop/quick copy citations in `LaTeX` format. Set the
        desired LaTeX citation command here. If you set this to `citep`,
        drag-and-drop citations will yield `\citep{key1,key2,...}`
    Surround Pandoc citations with brackets:
      default: 'false'
      description: >-
        Used for drag-and-drop/quick copy citations in `Pandoc` format. You can
        use this option to select whether you want to have these pandoc
        citations surrounded with brackets or not.
    Citation key format:
      default: '"â€‹[auth:lower][shorttitle3_3][year]"'
      description: >-
        Set the pattern used to generate citation keys. The format of the keys
        is documented [here](citation-keys).
    Force citation key to plain text:
      default: 'true'
      description: >-
        If you have deviated from the default citation key format pattern by
        [specifying your own](citation-keys), you may wind up with non-ASCII
        characters in your citation keys. You can prevent that using the `fold`
        function at the appropriate place in your pattern, but checking this
        checkbox will just apply `fold` to all your keys.
    'On conflict with a pinned key, non-pinned keys will be':
      default: kept (causes key duplicates)
      description: >-
        This determines what happens if you pin a key to a value that is already
        in use in a different reference but not pinned there. Neither are ideal,
        you just get to pick your poison. If you let BBT change the non-pinned
        key by adding a postfix character, the citation key changes which could
        be problematic for existing papers.  if you keep the non-pinned key
        as-is, your library now has duplicate keys.
      options:
        - postfixed (causes key changes)
        - kept (causes key duplicates)
    Keep keys unique:
      default: within each library
      description: >-
        This determines what happens if you pin a key to a value that is already
        in use in a different reference but not pinned there. Neither are ideal,
        you just get to pick your poison. If you let BBT change the non-pinned
        key by adding a postfix character, the citation key changes which could
        be problematic for existing papers.  if you keep the non-pinned key
        as-is, your library now has duplicate keys.
      options:
        - across all libraries
        - within each library
- name: Export
  description: ''
  preferences:
    'When a reference has both a DOI and a URL, export':
      default: both
      description: >-
        Does what it says on the tin, really. If a reference has both a DOI and
        an URL, you can choose to have them both exported, or either one of
        them.
      options:
        - both
        - DOI
        - URL
    Export unicode as plain-text latex commands:
      default: 'false'
      description: >-
        BibLaTeX actually has really good Unicode support, so you generally want
        this off. But for some geezers such as me it is simply more pleasing to
        have things like accented characters translated to their equivalent
        LaTeX constructs on export.
    Export unicode as plain-text latex commands (recommended):
      default: 'true'
      description: >-
        BibTeX has really spotty Unicode support, so you generally want this on.
        It will translate things like accented characters to their equivalent
        LaTeX constructs on export.
    'Assume single-word strings to be externally-defined @string vars, and thus not surrounded by braces':
      default: 'false'
      description: >-
        When enabled, single-word strings will be assumed to be
        externally-defined @string vars, and thus not surrounded by braces. If
        you don't know what this means, leave it off.
    Disregard name prefixes when sorting:
      default: 'false'
      description: >-
        Name handling is a lot more complex than I had ever thought it to be. A
        *lot* more complex. BibTeX has really limited ways of dealing with names
        with particles (van, von, de, etc). If you turn this on, BBT will add
        code to have `van Gogh` sorted under `Gogh`.
    Fields to omit from export (comma-separated):
      default: '""'
      description: >-
        If there are some fields you don't want in your bibtex files (such as
        `note` for example), add a list of them here, separated by comma's.
    Add URLs to BibTeX export:
      default: 'no'
      description: >-
        BibLaTeX supports urls in your references natively; BibTeX does not. For
        this reason, URLs are omitted from BibTeX exports by default. Using this
        setting you can have them added to your exports either in a `note` field
        (not as clean, but compatible with BibTeX out of the box), or in a `url`
        field (requires extra packages to be loaded, or bibtex will error out).
      options:
        - 'no'
        - in a note field
        - in a URL field
    'Abbreviation style:':
      default: 'false'
      description: >-
        If set, generates journal abbreviations on export using the Zotero
        journal abbreviator, according to the abbreviation style selected in the
        list below the checkbox.
    'Include JabRef-specific metadata:':
      default: 'no'
      description: >-
        Export JabRef-specific information fields; timetamps and groups for
        collections.
      options:
        - 'no'
        - for JabRef 3
        - for JabRef 4
    Include comments about potential problems with the references:
      default: 'false'
      description: Generate quality reports for exported references.
    Use BibLaTeX extended name format (requires biblatex 3.5):
      default: 'false'
      description: >-
        Use the extended biber 2.7 format for names with particles - only works
        in BibLaTeX 3.5 or later. This biblatex has a new (less ambiguous) way
        to store creator names. It's technically superior, but the LaTeX world
        moves slowly, so many people won't have it yet. But if you're an early
        adopter, you can enable it here
- name: Automatic export
  description: ''
  preferences:
    Automatic export:
      default: On Change
      description: >-
        Determines when [automatic exports](push-and-pull) are kicked off.
        Having it disabled still marks auto-exports as needing updates, so when
        you re-enable it, those exports will start. On-change means exports
        happen whenever a reference in the export changes/is added/is removed.
        On idle does more or less what `Disabled` (that is, no exports but mark
        as needing changes), but will kick off exports when your computer is
        idle. You mostly want this if your computer is performance-constrained
        (aka slow).
      options:
        - Disabled
        - On Change
        - When Idle
- name: Advanced
  description: ''
  preferences:
    Warn me when changing citation keys in bulk:
      default: '10'
      description: >-
        For those who are curious about what the "Clear/Generate BibTeX key"
        right-click options do, this will warn you if you are doing this on more
        than 10 (default) at the same time, to prevent your curiosity from
        changing all your citation keys at once.
    postscript:
      default: '""'
      description: >-
        Snippet of javascript to run [after each reference
        generation](scripting).
    import @string definitions:
      default: '""'
      description: >-
        If you have externally maintained @string vars paste them here and they
        will be resolved for subsequent imports
- name: Hidden preferences
  description: >-
    The following settings are not exposed in the UI, but can be found under
    `Preferences`/`Advanced`/`Config editor`.


    All are prefixed with `extensions.zotero.translators.better-bibtex.` in the
    table you will find there
  preferences:
    autoAbbrevStyle:
      default: '""'
      description: >-
        Select the style for auto-abbreviation. Only applicable to Juris-M; in
        Zotero, the style for automatic abbreviation is not configurable.
    autoExportIdleWait:
      default: '10'
      description: >-
        Number of seconds to wait after your system goes idle before kicking off
        auto-exports.
    cacheFlushInterval:
      default: '5'
      description: >-
        How often the Better BibTeX database should be saved to disk. Defaults
        to once every 5 seconds. Note that your database is always saved when
        your computer goes idle, or when you exit Zotero.
    csquotes:
      default: '""'
      description: >-
        if you set `csquotes` to a string of character pairs, each pair will be
        assumed to be the open and close parts of a pair and will be replaced
        with a `\\enquote{...}` construct.
    skipWords:
      default: >-
        "a,ab,aboard,about,above,across,after,against,al,along,amid,among,an,and,anti,around,as,at,before,behind,below,beneath,beside,besides,between,beyond,but,by,d,da,das,de,del,dell,dello,dei,degli,della,dell,delle,dem,den,der,des,despite,die,do,down,du,during,ein,eine,einem,einen,einer,eines,el,en,et,except,for,from,gli,i,il,in,inside,into,is,l,la,las,le,les,like,lo,los,near,nor,of,off,on,onto,or,over,past,per,plus,round,save,since,so,some,sur,than,the,through,to,toward,towards,un,una,unas,under,underneath,une,unlike,uno,unos,until,up,upon,versus,via,von,while,with,within,without,yet,zu,zum"
      description: list of words to skip in title when generating citation keys
    biblatexExtendedDateFormat:
      default: 'true'
      description: Support for EDTF dates in biblatex
    suppressTitleCase:
      default: 'false'
      description: >-
        If you're dead-set on ignoring both BibTeX/BibLaTeX best practice and
        the Zotero recommendations on title/sentence casing, set this preference
        to "true" to suppress [title casing for English
        references](Unnecessarily-complicated-BibTeX-output%3F#mapping-fields).
    parseParticles:
      default: 'true'
      description: Name particle handling
    citeprocNoteCitekey:
      default: 'false'
      description: >-
        Replaces the "note" field with the bibtex key during citation rendering
        in Word/Libreoffice. Main use-case is to help migrating word documents
        to pandoc. This setting only takes effect during startup, so if you
        change it, you will have to restart Zotero to have this take effect (or
        to disable it. Please disable it when done). You will want to use a
        custom CSL style (such as
        [this](https://raw.githubusercontent.com/retorquere/zotero-better-bibtex/master/better-bibtex-citekeys.csl))
        to make this work.
    scrubDatabase:
      default: 'false'
      description: >-
        Finds potential problems in the database and fixes those. This runs
        **extremely** slow at startup, don't unable this unless explicitly asked
        to.
    autoPin:
      default: 'false'
      description: >-
        When on, BBT will automatically pin the first citekey it generates for
        an item.
    kuroshiro:
      default: 'false'
      description: >-
        When on, BBT will load kuroshiro for romajization in citekeys. This uses
        a lot of memory, easily 100MB. If you don't have Japanese titles/names,
        keep this off.
    sorted:
      default: 'false'
      description: >-
        When on, BBT will sort references on the citekey. Comes at performance
        and memory consumption cost.
