name: 'Manage issues and nag about debug logs'

on:
  issues:
    types: [opened, edited, closed, reopened]
  issue_comment:
    types: [created, edited, closed]
  workflow_dispatch:

jobs:
  nag:
    runs-on: ubuntu-latest
    steps:
      - uses: retorquere/label-gun@main
        with:
          token: ${{ github.token }}
          label.exempt: question
          label.awaiting: awaiting-user-feedback
          label.reopened: reopened
          log.regex: "([A-Z0-9]{8}(-refs)?-(apse|euc))|([A-Z0-9]{8}-[^-]+)"
          log.label: needs-debug-log
          log.message: |
            Hello @{{username}},

            `@retorquere` is ready to assist you with Better BibTeX. In order to do so efficiently, a debug log is generally required. The information it containst is key to him understanding, replicating, and resolving your issue. If you have shared a `D<number>` log, those go to the Zotero team, `@retorquere` cannot access those.

            **Here’s how you can share your debug log:**

            1. If your issue involves specific references, citekey generation, or exports, right-click on the relevant item(s) and select "Better BibTeX -> Submit Better BibTeX debug log" from the menu.
            2. For issues where items do not play a role, follow these steps:
              * Restart Zotero with debugging enabled (Help -> Debug Output Logging -> Restart with logging enabled).
              * Reproduce the problem.
              * Choose "Send Better BibTeX debug report..." from the help menu.

            After these steps, you will receive debug ID displayed in red. Please share this ID with `@retorquere` in this issue thread. If your query is about an export, include both the actually exported result and your expected/desired outcome.

            Sharing your debug log gives `@retorquere` a view of your Better BibTeX configuration and the elements contributing to the issue. This helps him address your concerns more efficiently.

            If you have submitted a debug log and its ID looks like `D<number>`, that debug log goes to the Zotero team, not to `@retorquere`. Please see the points above how to send a BBT debug log.

            Thank you.

            **PS: If the Debug Log menu is not available, or if it fails to send the debug log**, you can use the option under “Help” > “Send debug log to file.io”.

          close.message: Thanks for the feedback! Just so you know, GitHub doesn't let me control who can close issues, and @retorquere likes to leave bug reports and enhancements open as a nudge to merge them into the next release.

          verbose: true
          assign: true
